### ISSUE TITLE
Probabile refuso in 8-consigli-sulla-produttivita-per-sviluppatori-e-programmatori

### ISSUE THREAD

**Issue by progressify** [alby-dev/alby-dev.github.io#1]
In questa pagina:
https://github.com/alby-dev/alby-dev.github.io/blob/main/content/italian/blog/2022-07-22-8-consigli-sulla-produttivita-per-sviluppatori-e-programmatori.md

Alla fine c'è questo testo:

```
{{- /* This comment removes trailing newlines. */ -}}
```

**Comment by alby-dev** [comment]
Grazie @progressify! Mi deve essere scappato un "incolla"! Ora l'ho corretto grazie!

**Comment by progressify** [comment]
LGTM
